
def init():
    global b_show_histos
    global b_histo
    global current_tracking_frame
    global threshLoHsv
    global threshHiHsv
    global threshLoRgb
    global threshHiRgb
    global b_show_puase_rect
    global b_thresh_rgb
    global b_thresh_hsv
    global thresh_pct
    global thresh_log
    global gui_pass1
    global gui_cmd_quit
    global sw_agenda
    global gui_cmd_combine
    global gui_cmd_reset_agenda
    global gui_cmd_set_rgb
    global gui_cmd_set_hsv
