def init():
    global gui_cmd_quit
    global gui_cmd_record
    global gui_cmd_reset
    global gui_unique_fn
    global gui_dir_path
    global sw_record_start
    global sw_record_stop
    global sw_gui_dir
    global gui_b_jumpcut
    global b_jumpcut_inprogress
    global sw_preview_frame
    global gui_b_preview_frame
    global sw_camera_reset
    global gui_frame_size_enum
    global gui_cam_num
    global gui_b_resize
    global gui_codec_enum
    global gui_b_buffer
    global gui_log_enum

    global playOn
    global switchAdvanceFrame
    global switchRetreatFrame
