def init():
    global playOn
    global switchAdvanceFrame
    global switchRetreatFrame
    global switchRewind
    global switchFastforward
    global frameDelay
    global callExit
    global delaySecs
